### ISSUE TITLE
Impossible to use CLI

### ISSUE THREAD

**Issue by mcharlou** [LHEEA/meshmagick#26]
## Description
After installing Meshmagick using `setup.py` with option `--prefix ~/.local`, any call to Meshmagick in CLI fails with the following error:
```
Traceback (most recent call last):
  File "/home/user_name/.local/bin/meshmagick", line 11, in <module>
    load_entry_point('meshmagick==2.1.1', 'console_scripts', 'meshmagick')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'meshmagick_cli'
```

## Configuration
OS: Debian 10 (Buster)
Python: 3.7.3

**Comment by mcharlou** [comment]
A similar error occurs when installing without option `--prefix ~/.local` in Docker image `python:3.7-buster`:
```
Traceback (most recent call last):
  File "/usr/local/bin/meshmagick", line 33, in <module>
    sys.exit(load_entry_point('meshmagick==2.1.1', 'console_scripts', 'meshmagick')())
  File "/usr/local/bin/meshmagick", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.7/site-packages/importlib_metadata-4.0.1-py3.7.egg/importlib_metadata/__init__.py", line 166, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'meshmagick_cli'
```

Here are the installation logs in case it's of any relevance (`python setup.py install`):
```
running install
running bdist_egg
running egg_info
creating meshmagick.egg-info
writing meshmagick.egg-info/PKG-INFO
writing dependency_links to meshmagick.egg-info/dependency_links.txt
writing entry points to meshmagick.egg-info/entry_points.txt
writing requirements to meshmagick.egg-info/requires.txt
writing top-level names to meshmagick.egg-info/top_level.txt
writing manifest file 'meshmagick.egg-info/SOURCES.txt'
adding license file 'LICENCE' (matched pattern 'LICEN[CS]E*')
reading manifest file 'meshmagick.egg-info/SOURCES.txt'
writing manifest file 'meshmagick.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/meshmagick
copying meshmagick/mmio.py -> build/lib/meshmagick
copying meshmagick/mesh_clipper.py -> build/lib/meshmagick
copying meshmagick/__init__.py -> build/lib/meshmagick
copying meshmagick/mesh.py -> build/lib/meshmagick
copying meshmagick/inertia.py -> build/lib/meshmagick
copying meshmagick/MMviewer.py -> build/lib/meshmagick
copying meshmagick/hydrostatics.py -> build/lib/meshmagick
copying meshmagick/tools.py -> build/lib/meshmagick
copying meshmagick/densities.py -> build/lib/meshmagick
creating build/lib/meshmagick/tests
copying meshmagick/tests/__init__.py -> build/lib/meshmagick/tests
copying meshmagick/tests/test_IO.py -> build/lib/meshmagick/tests
copying meshmagick/tests/test_hydrostatics.py -> build/lib/meshmagick/tests
copying meshmagick/tests/test_inertia.py -> build/lib/meshmagick/tests
copying meshmagick/tests/test_inertia_cylinder.py -> build/lib/meshmagick/tests
copying meshmagick/tests/test_mesh.py -> build/lib/meshmagick/tests
copying meshmagick/tests/test_clipping.py -> build/lib/meshmagick/tests
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/meshmagick
copying build/lib/meshmagick/mmio.py -> build/bdist.linux-x86_64/egg/meshmagick
copying build/lib/meshmagick/mesh_clipper.py -> build/bdist.linux-x86_64/egg/meshmagick
copying build/lib/meshmagick/__init__.py -> build/bdist.linux-x86_64/egg/meshmagick
creating build/bdist.linux-x86_64/egg/meshmagick/tests
copying build/lib/meshmagick/tests/__init__.py -> build/bdist.linux-x86_64/egg/meshmagick/tests
copying build/lib/meshmagick/tests/test_IO.py -> build/bdist.linux-x86_64/egg/meshmagick/tests
copying build/lib/meshmagick/tests/test_hydrostatics.py -> build/bdist.linux-x86_64/egg/meshmagick/tests
copying build/lib/meshmagick/tests/test_inertia.py -> build/bdist.linux-x86_64/egg/meshmagick/tests
copying build/lib/meshmagick/tests/test_inertia_cylinder.py -> build/bdist.linux-x86_64/egg/meshmagick/tests
copying build/lib/meshmagick/tests/test_mesh.py -> build/bdist.linux-x86_64/egg/meshmagick/tests
copying build/lib/meshmagick/tests/test_clipping.py -> build/bdist.linux-x86_64/egg/meshmagick/tests
copying build/lib/meshmagick/mesh.py -> build/bdist.linux-x86_64/egg/meshmagick
copying build/lib/meshmagick/inertia.py -> build/bdist.linux-x86_64/egg/meshmagick
copying build/lib/meshmagick/MMviewer.py -> build/bdist.linux-x86_64/egg/meshmagick
copying build/lib/meshmagick/hydrostatics.py -> build/bdist.linux-x86_64/egg/meshmagick
copying build/lib/meshmagick/tools.py -> build/bdist.linux-x86_64/egg/meshmagick
copying build/lib/meshmagick/densities.py -> build/bdist.linux-x86_64/egg/meshmagick
byte-compiling build/bdist.linux-x86_64/egg/meshmagick/mmio.py to mmio.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/meshmagick/mesh_clipper.py to mesh_clipper.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/meshmagick/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/meshmagick/tests/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/meshmagick/tests/test_IO.py to test_IO.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/meshmagick/tests/test_hydrostatics.py to test_hydrostatics.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/meshmagick/tests/test_inertia.py to test_inertia.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/meshmagick/tests/test_inertia_cylinder.py to test_inertia_cylinder.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/meshmagick/tests/test_mesh.py to test_mesh.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/meshmagick/tests/test_clipping.py to test_clipping.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/meshmagick/mesh.py to mesh.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/meshmagick/inertia.py to inertia.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/meshmagick/MMviewer.py to MMviewer.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/meshmagick/hydrostatics.py to hydrostatics.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/meshmagick/tools.py to tools.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/meshmagick/densities.py to densities.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying meshmagick.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying meshmagick.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying meshmagick.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying meshmagick.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying meshmagick.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying meshmagick.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/meshmagick-2.1.1-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing meshmagick-2.1.1-py3.7.egg
Copying meshmagick-2.1.1-py3.7.egg to /usr/local/lib/python3.7/site-packages
Adding meshmagick 2.1.1 to easy-install.pth file
Installing meshmagick script to /usr/local/bin

Installed /usr/local/lib/python3.7/site-packages/meshmagick-2.1.1-py3.7.egg
Processing dependencies for meshmagick==2.1.1
Searching for argcomplete
Reading https://pypi.org/simple/argcomplete/
Downloading https://files.pythonhosted.org/packages/b7/9e/9dc74d330c07866d72f62d553fe8bdbe32786ff247a14e68b5659963e6bd/argcomplete-1.12.3-py2.py3-none-any.whl#sha256=291f0beca7fd49ce285d2f10e4c1c77e9460cf823eef2de54df0c0fec88b0d81
Best match: argcomplete 1.12.3
Processing argcomplete-1.12.3-py2.py3-none-any.whl
Installing argcomplete-1.12.3-py2.py3-none-any.whl to /usr/local/lib/python3.7/site-packages
Adding argcomplete 1.12.3 to easy-install.pth file
Installing activate-global-python-argcomplete script to /usr/local/bin
Installing python-argcomplete-check-easy-install-script script to /usr/local/bin
Installing register-python-argcomplete script to /usr/local/bin
Installing python-argcomplete-tcsh script to /usr/local/bin

Installed /usr/local/lib/python3.7/site-packages/argcomplete-1.12.3-py3.7.egg
Searching for numpy
Reading https://pypi.org/simple/numpy/
Downloading https://files.pythonhosted.org/packages/a9/03/5b216f6a55ffc6bdac3ad3a896c58d4f17d99e18ff82fc68363df7d6a7b3/numpy-1.20.2-cp37-cp37m-manylinux1_x86_64.whl#sha256=9cab23439eb1ebfed1aaec9cd42b7dc50fc96d5cd3147da348d9161f0501ada5
Best match: numpy 1.20.2
Processing numpy-1.20.2-cp37-cp37m-manylinux1_x86_64.whl
Installing numpy-1.20.2-cp37-cp37m-manylinux1_x86_64.whl to /usr/local/lib/python3.7/site-packages
Adding numpy 1.20.2 to easy-install.pth file
Installing f2py script to /usr/local/bin
Installing f2py3 script to /usr/local/bin
Installing f2py3.7 script to /usr/local/bin

Installed /usr/local/lib/python3.7/site-packages/numpy-1.20.2-py3.7-linux-x86_64.egg
Searching for importlib-metadata<5,>=0.23
Reading https://pypi.org/simple/importlib-metadata/
Downloading https://files.pythonhosted.org/packages/8e/e2/49966924c93909d47612bb47d911448140a2f6c1390aec2f4c1afbe3748f/importlib_metadata-4.0.1-py3-none-any.whl#sha256=d7eb1dea6d6a6086f8be21784cc9e3bcfa55872b52309bc5fad53a8ea444465d
Best match: importlib-metadata 4.0.1
Processing importlib_metadata-4.0.1-py3-none-any.whl
Installing importlib_metadata-4.0.1-py3-none-any.whl to /usr/local/lib/python3.7/site-packages
Adding importlib-metadata 4.0.1 to easy-install.pth file

Installed /usr/local/lib/python3.7/site-packages/importlib_metadata-4.0.1-py3.7.egg
Searching for zipp>=0.5
Reading https://pypi.org/simple/zipp/
Downloading https://files.pythonhosted.org/packages/0f/8c/715c54e9e34c0c4820f616a913a7de3337d0cd79074dd1bed4dd840f16ae/zipp-3.4.1-py3-none-any.whl#sha256=51cb66cc54621609dd593d1787f286ee42a5c0adbb4b29abea5a63edc3e03098
Best match: zipp 3.4.1
Processing zipp-3.4.1-py3-none-any.whl
Installing zipp-3.4.1-py3-none-any.whl to /usr/local/lib/python3.7/site-packages
Adding zipp 3.4.1 to easy-install.pth file

Installed /usr/local/lib/python3.7/site-packages/zipp-3.4.1-py3.7.egg
Searching for typing-extensions>=3.6.4
Reading https://pypi.org/simple/typing-extensions/
Downloading https://files.pythonhosted.org/packages/2e/35/6c4fff5ab443b57116cb1aad46421fb719bed2825664e8fe77d66d99bcbc/typing_extensions-3.10.0.0-py3-none-any.whl#sha256=779383f6086d90c99ae41cf0ff39aac8a7937a9283ce0a414e5dd782f4c94a84
Best match: typing-extensions 3.10.0.0
Processing typing_extensions-3.10.0.0-py3-none-any.whl
Installing typing_extensions-3.10.0.0-py3-none-any.whl to /usr/local/lib/python3.7/site-packages
Adding typing-extensions 3.10.0.0 to easy-install.pth file

Installed /usr/local/lib/python3.7/site-packages/typing_extensions-3.10.0.0-py3.7.egg
Searching for vtk==9.0.1
Best match: vtk 9.0.1
Adding vtk 9.0.1 to easy-install.pth file

Using /usr/local/lib/python3.7/site-packages
Finished processing dependencies for meshmagick==2.1.1
```

**Comment by frongere** [comment]
Please use the install procedure using pip and described [here](https://lheea.github.io/meshmagick/install/install.html#installing-from-source)

`pip install -e .`

I also advise relying on the python [miniconda](https://docs.conda.io/en/latest/miniconda.html#linux-installers) distribution instead of Debian repositories.

**Comment by mcharlou** [comment]
Seems to work fine with the alternate method of installation!

Is the other method no longer supported?

**Comment by frongere** [comment]
Install via pip works fine but install with conda is not currently maintained as I did not setup a CI yet to deploy automatically new versions on anaconda cloud. Installing via conda install command will at best install an old version of meshmagick.
I have to update the documentation.

**Comment by mcharlou** [comment]
I was thinking about the `python setup.py install` way, which is the recommended way for installing meshmagick without tracking changes to the code, according to the documentation... This isn't the conda way, right? I'm not familiar with `setuptools`, but I guess it's the culprit if `setup.py` doesn't work.

But anyway, thanks for the info, it's working fine now!

**Comment by mancellin** [comment]
> I did not setup a CI yet to deploy automatically new versions on anaconda cloud

Just FYI, I can recommend conda-forge. Building and publishing new versions with their CI has always been seamless for me.

**Comment by frongere** [comment]
Thanks for this Matthieu :)

**Comment by frongere** [comment]
@mcharlou, not the conda way indeed. But I never use directly setuptools. Definitely, documentation needs a cleaning... No time for it for the moment though
