### ISSUE TITLE
Meshmagick Hydrostatic Issue

### ISSUE THREAD

**Issue by battuta** [LHEEA/meshmagick#30]
```
C:\Users\User\Geometry>meshmagick H1.stl -hs

=============================================
meshmagick - version 3.0
Copyright 2014-2021, Ecole Centrale de Nantes / D-ICE Engineering
=============================================
H1.stl successfully loaded
>>>> Performing hydrostatic computation on the current hull configuration considered at equilibrium
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Scripts\meshmagick-script.py", line 33, in <module>
    sys.exit(load_entry_point('meshmagick', 'console_scripts', 'meshmagick')())
  File "c:\program files\meshmagick3\meshmagick_cli.py", line 1196, in main
    raise RuntimeError("zcog should at least be given for correct stiffness values computations")
RuntimeError: zcog should at least be given for correct stiffness values computations
```

**Comment by battuta** [comment]
Center of gravity must be manually identified in order to calculate hydrostatics of STL files
`meshmagick H1.stl --cog 0 0 0 -hs`
