### ISSUE TITLE
load_GDF ValueError

### ISSUE THREAD

**Issue by michaelcdevin** [LHEEA/meshmagick#31]
When trying to read in a gdf file into the program using `meshmagic.mmio.load_GDF`, I am getting the following error:

```
Traceback (most recent call last):
  File "C:\code\testbed\wamit_capytaine_compare.py", line 83, in <module>
    mesh_vertices, mesh_faces = mmio.load_GDF(gdf_file)
  File "C:\Users\mcdevin\Miniconda3\envs\OWENS\lib\site-packages\meshmagick\mmio.py", line 785, in load_GDF
    vertices[iv, :] = np.array(ifile.readline().split())[:3]
ValueError: could not broadcast input array from shape (0,) into shape (3,)
```

I checked the GDF file in question and it appears to be properly formatted.

**Comment by michaelcdevin** [comment]
I discovered the problem I was having. If I'm understanding the code correctly, `load_GDF` assumes that each point is contained on its own line, so each face consists of four lines before moving on to the next face. For example:

```
X1(1)   Y1(1)   Z1(1)
X2(1)   Y2(1)   Z2(1)
X3(1)   Y3(1)   Z3(1)
X4(1)   Y4(1)   Z4(1)
X2(1)   Y2(1)   Z2(1)
X2(2)   Y2(2)   Z3(2)
...
X4(nf)  Y4(nf)  Z4(nf)
```

My GDF file contains all four points of each face on one line:
```
X1(1)   Y1(1)   Z1(1)   X2(1)   Y2(1)   Z2(1)   X3(1)   Y3(1)   Z3(1)   X4(1)   Y4(1)   Z4(1)
X1(2)   Y1(2)   Z1(2)   X2(2)   Y2(2)   Z2(2)   X3(2)   Y3(2)   Z3(2)   X4(2)   Y4(2)   Z4(2)
...
X1(nf)  Y1(nf)  Z1(nf)  X2(nf)  Y2(nf)  Z2(nf)  X3(nf)  Y3(nf)  Z3(nf)  X4(nf)  Y4(nf)  Z4(nf)
```

According to the [WAMIT documentation](https://www.wamit.com/manualupdate/V70_manual.pdf#page=94), line breaks must exist between faces, but additional line breaks can also be used without effect, so either format above is acceptable. However, `load_GDF` starts returning empty arrays once it reaches the end of the file with the second format because it is trying to read four times as many lines as the GDF file contains, resulting in the `ValueError` I encountered.

I modified my local version of `meshmagick.mmio.load_GDF` to generalize how it reads the points in the file so either format is acceptable (or really any format as long as there is a line break at the end of each face). I will create a pull request with my changes.
