### ISSUE TITLE
ModuleNotFoundError: No module named 'gmshparser'

### ISSUE THREAD

**Issue by Kajitrim** [LHEEA/meshmagick#39]
Hello all,
In python, I used the following to read a gmsh .msh file:
``
from meshmagick import mmio
mmio.load_MSH('../Mesh/test.MSH')
``
The following error appeared:
``
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3.3\plugins\python-ce\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "c:\users\acerisier\documents\nemoh\meshmagick\meshmagick\mmio.py", line 949, in load_MSH
    return load_MSH41(filename)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\users\acerisier\documents\nemoh\meshmagick\meshmagick\mmio.py", line 883, in load_MSH41
    import gmshparser
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'gmshparser'
``
Can someone help please?

**Comment by Kajitrim** [comment]
Stupid mistake, I just had to install the gmshparser library from Pypi, my bad!
